static char *glade_data =
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
    "<!-- Generated with glade 3.22.1 -->\n"
    "<interface>\n"
    "  <requires lib=\"gtk+\" version=\"3.20\"/>\n"
    "  <object class=\"GtkWindow\" id=\"add_window\">\n"
    "    <property name=\"can_focus\">False</property>\n"
    "    <child>\n"
    "      <placeholder/>\n"
    "    </child>\n"
    "    <child>\n"
    "      <object class=\"GtkBox\">\n"
    "        <property name=\"visible\">True</property>\n"
    "        <property name=\"can_focus\">False</property>\n"
    "        <property name=\"orientation\">vertical</property>\n"
    "        <child>\n"
    "          <object class=\"GtkGrid\">\n"
    "            <property name=\"visible\">True</property>\n"
    "            <property name=\"can_focus\">False</property>\n"
    "            <property name=\"row_spacing\">10</property>\n"
    "            <property name=\"column_spacing\">2</property>\n"
    "            <property name=\"row_homogeneous\">True</property>\n"
    "            <child>\n"
    "              <object class=\"GtkLabel\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">False</property>\n"
    "                <property name=\"tooltip_markup\" translatable=\"yes\">Leave blank unless connecting via an RDP Gateway</property>\n"
    "                <property name=\"halign\">end</property>\n"
    "                <property name=\"label\" translatable=\"yes\">Gateway:</property>\n"
    "                <property name=\"justify\">right</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">0</property>\n"
    "                <property name=\"top_attach\">6</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkLabel\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">False</property>\n"
    "                <property name=\"halign\">end</property>\n"
    "                <property name=\"label\" translatable=\"yes\">Gateway Port:</property>\n"
    "                <property name=\"justify\">right</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">0</property>\n"
    "                <property name=\"top_attach\">7</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkLabel\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">False</property>\n"
    "                <property name=\"halign\">end</property>\n"
    "                <property name=\"label\" translatable=\"yes\">Gateway Username:</property>\n"
    "                <property name=\"justify\">right</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">0</property>\n"
    "                <property name=\"top_attach\">8</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkLabel\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">False</property>\n"
    "                <property name=\"halign\">end</property>\n"
    "                <property name=\"label\" translatable=\"yes\">Host:</property>\n"
    "                <property name=\"justify\">right</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">0</property>\n"
    "                <property name=\"top_attach\">1</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkLabel\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">False</property>\n"
    "                <property name=\"halign\">end</property>\n"
    "                <property name=\"label\" translatable=\"yes\">Host Port:</property>\n"
    "                <property name=\"justify\">right</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">0</property>\n"
    "                <property name=\"top_attach\">2</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkLabel\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">False</property>\n"
    "                <property name=\"halign\">end</property>\n"
    "                <property name=\"label\" translatable=\"yes\">Username:</property>\n"
    "                <property name=\"justify\">right</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">0</property>\n"
    "                <property name=\"top_attach\">3</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkEntry\" id=\"gw_port\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"halign\">start</property>\n"
    "                <property name=\"max_length\">5</property>\n"
    "                <property name=\"width_chars\">5</property>\n"
    "                <property name=\"max_width_chars\">5</property>\n"
    "                <property name=\"text\" translatable=\"yes\">443</property>\n"
    "                <property name=\"input_purpose\">number</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">1</property>\n"
    "                <property name=\"top_attach\">7</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkEntry\" id=\"gw_host\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"tooltip_text\" translatable=\"yes\">Leave this blank unless you are connecting via an RDP Gateway</property>\n"
    "                <property name=\"width_chars\">32</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">1</property>\n"
    "                <property name=\"top_attach\">6</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkEntry\" id=\"gw_username\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"tooltip_text\" translatable=\"yes\">Of the form domain\\username. Will be used to authenticate to the RDP Gateway. If blank the \"Username\" field will be used.</property>\n"
    "                <property name=\"width_chars\">32</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">1</property>\n"
    "                <property name=\"top_attach\">8</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkEntry\" id=\"host\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"tooltip_text\" translatable=\"yes\">The host to which you are trying to connect.</property>\n"
    "                <property name=\"width_chars\">32</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">1</property>\n"
    "                <property name=\"top_attach\">1</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkEntry\" id=\"port\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"halign\">start</property>\n"
    "                <property name=\"max_length\">5</property>\n"
    "                <property name=\"width_chars\">5</property>\n"
    "                <property name=\"max_width_chars\">5</property>\n"
    "                <property name=\"text\" translatable=\"yes\">3389</property>\n"
    "                <property name=\"input_purpose\">number</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">1</property>\n"
    "                <property name=\"top_attach\">2</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkEntry\" id=\"username\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"tooltip_text\" translatable=\"yes\">Of the form domain\\username. Will be used to authenticate to the destination host.</property>\n"
    "                <property name=\"width_chars\">32</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">1</property>\n"
    "                <property name=\"top_attach\">3</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkLabel\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">False</property>\n"
    "                <property name=\"halign\">end</property>\n"
    "                <property name=\"label\" translatable=\"yes\">Entry Name:</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">0</property>\n"
    "                <property name=\"top_attach\">0</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkEntry\" id=\"entry_name\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"tooltip_text\" translatable=\"yes\">A human-readable name for this entry. Can be anything you want.</property>\n"
    "                <property name=\"width_chars\">32</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">1</property>\n"
    "                <property name=\"top_attach\">0</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkLabel\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">False</property>\n"
    "                <property name=\"halign\">end</property>\n"
    "                <property name=\"label\" translatable=\"yes\">Gateway Password:</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">0</property>\n"
    "                <property name=\"top_attach\">9</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkLabel\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">False</property>\n"
    "                <property name=\"halign\">end</property>\n"
    "                <property name=\"label\" translatable=\"yes\">Password:</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">0</property>\n"
    "                <property name=\"top_attach\">4</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkEntry\" id=\"password\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"visibility\">False</property>\n"
    "                <property name=\"invisible_char\">●</property>\n"
    "                <property name=\"input_purpose\">password</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">1</property>\n"
    "                <property name=\"top_attach\">4</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkEntry\" id=\"gw_password\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"tooltip_text\" translatable=\"yes\">The password for the gateway. If blank, the \"Password\" field will be used.</property>\n"
    "                <property name=\"visibility\">False</property>\n"
    "                <property name=\"invisible_char\">●</property>\n"
    "                <property name=\"input_purpose\">password</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">1</property>\n"
    "                <property name=\"top_attach\">9</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkLabel\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">False</property>\n"
    "                <property name=\"halign\">end</property>\n"
    "                <property name=\"label\" translatable=\"yes\">Display Size:</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">0</property>\n"
    "                <property name=\"top_attach\">5</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkEntry\" id=\"display_size\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"tooltip_text\" translatable=\"yes\">Size of display window in form WxH</property>\n"
    "                <property name=\"text\" translatable=\"yes\">1680x950</property>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"left_attach\">1</property>\n"
    "                <property name=\"top_attach\">5</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "          </object>\n"
    "          <packing>\n"
    "            <property name=\"expand\">True</property>\n"
    "            <property name=\"fill\">True</property>\n"
    "            <property name=\"position\">0</property>\n"
    "          </packing>\n"
    "        </child>\n"
    "        <child>\n"
    "          <object class=\"GtkSeparator\">\n"
    "            <property name=\"visible\">True</property>\n"
    "            <property name=\"can_focus\">False</property>\n"
    "          </object>\n"
    "          <packing>\n"
    "            <property name=\"expand\">False</property>\n"
    "            <property name=\"fill\">True</property>\n"
    "            <property name=\"padding\">10</property>\n"
    "            <property name=\"position\">1</property>\n"
    "          </packing>\n"
    "        </child>\n"
    "        <child>\n"
    "          <object class=\"GtkButtonBox\">\n"
    "            <property name=\"visible\">True</property>\n"
    "            <property name=\"can_focus\">False</property>\n"
    "            <property name=\"layout_style\">start</property>\n"
    "            <child>\n"
    "              <object class=\"GtkButton\" id=\"ok_button\">\n"
    "                <property name=\"label\" translatable=\"yes\">OK</property>\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"receives_default\">True</property>\n"
    "                <signal name=\"clicked\" handler=\"on_ok_button_clicked\" swapped=\"no\"/>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"expand\">True</property>\n"
    "                <property name=\"fill\">True</property>\n"
    "                <property name=\"position\">0</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkButton\" id=\"cancel_button\">\n"
    "                <property name=\"label\" translatable=\"yes\">Cancel</property>\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"receives_default\">True</property>\n"
    "                <signal name=\"clicked\" handler=\"on_cancel_button_clicked\" swapped=\"no\"/>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"expand\">True</property>\n"
    "                <property name=\"fill\">True</property>\n"
    "                <property name=\"position\">1</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkButton\" id=\"clear_button\">\n"
    "                <property name=\"label\" translatable=\"yes\">Clear</property>\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"receives_default\">True</property>\n"
    "                <signal name=\"clicked\" handler=\"on_clear_button_clicked\" swapped=\"no\"/>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"expand\">True</property>\n"
    "                <property name=\"fill\">True</property>\n"
    "                <property name=\"position\">2</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "          </object>\n"
    "          <packing>\n"
    "            <property name=\"expand\">False</property>\n"
    "            <property name=\"fill\">True</property>\n"
    "            <property name=\"position\">2</property>\n"
    "          </packing>\n"
    "        </child>\n"
    "      </object>\n"
    "    </child>\n"
    "  </object>\n"
    "  <object class=\"GtkWindow\" id=\"window1\">\n"
    "    <property name=\"can_focus\">False</property>\n"
    "    <property name=\"default_height\">500</property>\n"
    "    <signal name=\"delete-event\" handler=\"on_window1_delete_event\" swapped=\"no\"/>\n"
    "    <signal name=\"destroy\" handler=\"on_window1_destroy\" swapped=\"no\"/>\n"
    "    <child>\n"
    "      <placeholder/>\n"
    "    </child>\n"
    "    <child>\n"
    "      <object class=\"GtkBox\">\n"
    "        <property name=\"visible\">True</property>\n"
    "        <property name=\"can_focus\">False</property>\n"
    "        <property name=\"orientation\">vertical</property>\n"
    "        <child>\n"
    "          <object class=\"GtkScrolledWindow\">\n"
    "            <property name=\"visible\">True</property>\n"
    "            <property name=\"can_focus\">True</property>\n"
    "            <property name=\"shadow_type\">in</property>\n"
    "            <child>\n"
    "              <object class=\"GtkViewport\">\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">False</property>\n"
    "                <child>\n"
    "                  <object class=\"GtkListBox\" id=\"listbox\">\n"
    "                    <property name=\"visible\">True</property>\n"
    "                    <property name=\"can_focus\">False</property>\n"
    "                  </object>\n"
    "                </child>\n"
    "              </object>\n"
    "            </child>\n"
    "          </object>\n"
    "          <packing>\n"
    "            <property name=\"expand\">True</property>\n"
    "            <property name=\"fill\">True</property>\n"
    "            <property name=\"position\">0</property>\n"
    "          </packing>\n"
    "        </child>\n"
    "        <child>\n"
    "          <object class=\"GtkButtonBox\">\n"
    "            <property name=\"visible\">True</property>\n"
    "            <property name=\"can_focus\">False</property>\n"
    "            <property name=\"layout_style\">expand</property>\n"
    "            <child>\n"
    "              <object class=\"GtkButton\" id=\"quit_button\">\n"
    "                <property name=\"label\" translatable=\"yes\">Quit</property>\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"receives_default\">True</property>\n"
    "                <signal name=\"clicked\" handler=\"on_quit_button_clicked\" swapped=\"no\"/>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"expand\">True</property>\n"
    "                <property name=\"fill\">True</property>\n"
    "                <property name=\"position\">0</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkButton\" id=\"add_button\">\n"
    "                <property name=\"label\" translatable=\"yes\">Add</property>\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"receives_default\">True</property>\n"
    "                <signal name=\"clicked\" handler=\"on_add_button_clicked\" swapped=\"no\"/>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"expand\">True</property>\n"
    "                <property name=\"fill\">True</property>\n"
    "                <property name=\"position\">1</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkButton\" id=\"edit_button\">\n"
    "                <property name=\"label\" translatable=\"yes\">Edit</property>\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"receives_default\">True</property>\n"
    "                <signal name=\"clicked\" handler=\"on_edit_button_clicked\" swapped=\"no\"/>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"expand\">True</property>\n"
    "                <property name=\"fill\">True</property>\n"
    "                <property name=\"position\">2</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkButton\" id=\"delete_button\">\n"
    "                <property name=\"label\" translatable=\"yes\">Delete</property>\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"receives_default\">True</property>\n"
    "                <signal name=\"clicked\" handler=\"on_delete_button_clicked\" swapped=\"no\"/>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"expand\">True</property>\n"
    "                <property name=\"fill\">True</property>\n"
    "                <property name=\"position\">3</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "            <child>\n"
    "              <object class=\"GtkButton\" id=\"launch_button\">\n"
    "                <property name=\"label\" translatable=\"yes\">Launch</property>\n"
    "                <property name=\"visible\">True</property>\n"
    "                <property name=\"can_focus\">True</property>\n"
    "                <property name=\"receives_default\">True</property>\n"
    "                <signal name=\"clicked\" handler=\"on_launch_button_clicked\" swapped=\"no\"/>\n"
    "              </object>\n"
    "              <packing>\n"
    "                <property name=\"expand\">True</property>\n"
    "                <property name=\"fill\">True</property>\n"
    "                <property name=\"position\">4</property>\n"
    "              </packing>\n"
    "            </child>\n"
    "          </object>\n"
    "          <packing>\n"
    "            <property name=\"expand\">False</property>\n"
    "            <property name=\"fill\">True</property>\n"
    "            <property name=\"position\">1</property>\n"
    "          </packing>\n"
    "        </child>\n"
    "      </object>\n"
    "    </child>\n"
    "  </object>\n"
    "</interface>\n"
    ;
